id = "spiceflow-theme"
name = "Spiceflow Theme"
version = "0.1.3"
schema_version = 1
authors = ["Pyae Sone Aung <pyaesoneaungrgn@gmail.com>", "Clay Tercek"]
description = "Spiceflow themes for Zed"
repository = "https://github.com/PyaeSoneAungRgn/spiceflow-zed-theme"
